name: cd
on:
  status:
  workflow_dispatch:
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - name: Verify CI status
      uses: jglick/verify-ci-status-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release Drafter
      uses: release-drafter/release-drafter@v5.13.0
      with:
        name: next
        tag: next
        version: next
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check out
      uses: actions/checkout@v2.3.4
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Release
      uses: jglick/jenkins-maven-cd-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
